spring:
  profiles:
    active: local
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
      hibernate.default_batch_fetch_size: ${chunkSize:1000}

logging.path: logs/aws-beanstalk-tunning/

---
spring:
  profiles: local
  jpa:
    database-platform: H2
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: h2
    hikari:
      jdbc-url: jdbc:h2:mem://localhost/~/point;MVCC=TRUE
      username: sa
      password:
      driver-class-name: org.h2.Driver

  h2:
    console.enabled: true
    console.path: /h2-console
    console.settings.trace: false

---
spring:
  profiles: real
  datasource:
    hikari:
      maximum-pool-size: 50
      driver-class-name: org.mariadb.jdbc.Driver
server:
  tomcat:
    max-threads: 60
