spring:
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
      hibernate.default_batch_fetch_size: ${chunkSize:1000}

---
spring:
  profiles: local
  jpa:
    database-platform: H2
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: h2
    hikari:
      jdbc-url: jdbc:h2:mem://localhost/~/point;MVCC=TRUE
      username: sa
      password:
      driver-class-name: org.h2.Driver

  h2:
    console.enabled: true
    console.path: /h2-console #접속 URL -> jdbc:h2:mem:testdb, ID:sa, PW: (EMPTY)
    console.settings.trace: false

---
spring:
  profiles: real
  datasource:
    hikari:
      jdbc-url: jdbc:mariadb:aurora://point.cluster-cvqgfwbdqpys.ap-northeast-2.rds.amazonaws.com:3306/point
      username: point
      password: dndkgkspoint00!
      driver-class-name: org.mariadb.jdbc.Driver
      connectionTimeout: 10000
      max-lifetime: 600000
      maximumPoolSize: 200
      data-source-properties:
        connectTimeout: 10000
        socketTimeout: 60000